import { C } from "../core/constants";

export function AppStyles() {
  return (
    <style>{`
      @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap');
      :root{color-scheme:dark}
      *,*::before,*::after{box-sizing:border-box}
      *{transition:background-color .18s ease,border-color .18s ease,box-shadow .18s ease,opacity .18s ease}
      @keyframes fadeUp{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}
      @keyframes pulse{0%,100%{box-shadow:0 0 0 rgba(52,212,164,0)}50%{box-shadow:0 0 32px rgba(52,212,164,.22)}}
      body{margin:0;background:${C.bg};font-family:Manrope,ui-sans-serif,system-ui,sans-serif;font-size:13px;line-height:1.6;-webkit-font-smoothing:antialiased}
      button,input,select,textarea{font:inherit}
      h1,h2,h3,p{margin:0}
      .app{min-height:100vh;color:${C.text};background:radial-gradient(ellipse 80% 40% at 10% -5%,rgba(52,212,164,.10) 0,transparent 60%),radial-gradient(ellipse 60% 30% at 90% 0%,rgba(167,139,250,.07) 0,transparent 50%),${C.bg}}
      .loading{min-height:100vh;display:grid;place-items:center;background:${C.bg};color:${C.muted}}
      .topbar{position:sticky;top:0;z-index:20;display:flex;justify-content:space-between;align-items:center;padding:14px clamp(16px,3vw,32px);background:${C.overlay};backdrop-filter:blur(20px) saturate(1.5);border-bottom:1px solid ${C.border}}
      .brand{display:flex;gap:12px;align-items:center}.mark{width:38px;height:38px;border-radius:10px;display:grid;place-items:center;color:#08130f;background:${C.green};box-shadow:0 2px 12px rgba(52,212,164,.3)}
      .brand h1{font-size:17px;font-weight:700;letter-spacing:-.01em}.brand span,.soft-label,.meta-line{color:${C.muted};font-size:11px;font-weight:500}
      .header-actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.planning-badge{display:flex;align-items:center;gap:8px;padding:6px 12px;border:1px solid ${C.border};border-radius:9999px;background:${C.surface}}.planning-badge strong{color:${C.green};font-size:14px;font-weight:700;font-variant-numeric:tabular-nums}.planning-badge span{color:${C.muted};font-size:11px;font-weight:600;white-space:nowrap}
      .tabs{position:sticky;top:67px;z-index:19;display:flex;gap:0;overflow-x:auto;padding:0 clamp(16px,3vw,32px);background:${C.overlay};border-bottom:1px solid ${C.border};backdrop-filter:blur(20px) saturate(1.5);scrollbar-width:none}
      .tabs::-webkit-scrollbar{display:none}
      .tabs button{position:relative;border:0;background:transparent;color:${C.muted};padding:14px 14px 13px;border-bottom:2px solid transparent;display:flex;gap:6px;align-items:center;white-space:nowrap;cursor:pointer;font-weight:600;font-size:12px;letter-spacing:.01em;transition:color .15s}
      .tabs button:hover{color:${C.textDim};background:rgba(255,255,255,.03)}.tabs button.active{color:${C.text};border-color:${C.green}}.tabs button.needs-review{color:${C.amber}}.tab-count{min-width:16px;height:16px;border-radius:9999px;background:${C.amber};color:#16120a;display:grid;place-items:center;font-size:10px;font-weight:800}
      main{max-width:1360px;margin:0 auto;padding:32px clamp(16px,3vw,32px) 120px}
      .section-title{display:flex;justify-content:space-between;gap:14px;align-items:center;margin-bottom:20px}.section-heading{display:flex;gap:10px;align-items:center}.section-heading h2{font-size:20px;font-weight:700;letter-spacing:-.01em;color:${C.text}}
      .actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.btn{border:0;border-radius:8px;padding:8px 14px;font-weight:600;font-size:12px;letter-spacing:.01em;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:6px;color:${C.text};background:${C.raised};transition:transform .12s,filter .12s,background .12s}.btn:hover{transform:translateY(-1px);filter:brightness(1.12)}.btn:active{transform:translateY(0);filter:brightness(.95)}.btn.primary{background:${C.green};color:#071a12;font-weight:700;box-shadow:0 2px 10px rgba(52,212,164,.25)}.btn.primary:hover{box-shadow:0 4px 18px rgba(52,212,164,.35)}.btn.outline{background:transparent;border:1px solid ${C.border}}.btn.outline:hover{border-color:${C.borderHi};background:${C.raised}}.btn:disabled{opacity:.4;cursor:not-allowed;transform:none;filter:none}
      .card{min-width:0;background:linear-gradient(160deg,rgba(255,255,255,.04) 0%,rgba(255,255,255,0) 100%),${C.card};border:1px solid ${C.border};border-radius:16px;padding:20px;box-shadow:0 1px 0 rgba(255,255,255,.05) inset,0 4px 24px rgba(0,0,0,.28);margin-bottom:16px;backdrop-filter:blur(16px) saturate(1.3)}.card.accent{border-color:${C.purple}}
      .card-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:16px}.card-head h3,.card h3{font-size:14px;font-weight:700;letter-spacing:0}.card-head span{color:${C.muted};font-size:12px}.card p{color:${C.textDim};font-size:13px;line-height:1.65;margin-top:8px;white-space:pre-wrap}
      .field{width:100%;min-width:0;background:${C.surface};border:1px solid ${C.border};color:${C.text};border-radius:8px;padding:8px 10px;outline:0;transition:border-color .15s,box-shadow .15s}.field::placeholder{color:${C.muted}}.field:focus{border-color:${C.green};box-shadow:0 0 0 3px rgba(52,212,164,.14)}.field:hover:not(:focus){border-color:${C.borderHi}}.textarea{resize:vertical;line-height:1.6}
      .form-grid{display:grid;gap:8px;align-items:center}.task-grid{grid-template-columns:2fr 140px 1fr 1fr 80px 80px auto}.template-grid{grid-template-columns:2fr 1fr 1fr 80px auto}.routine-grid{grid-template-columns:2fr 120px 1fr auto}.goal-grid{grid-template-columns:2fr 1fr 140px 1fr 80px auto}.habit-add{grid-template-columns:1fr auto}
      .stack{display:flex;flex-direction:column;gap:8px}.block{margin-top:24px}.eyebrow{text-transform:uppercase;letter-spacing:.1em;font-size:10px;color:${C.muted};font-weight:700;margin:0 0 10px 2px;display:block}
      .task-row{display:grid;grid-template-columns:28px 24px minmax(180px,1fr) 100px 90px 140px 130px 38px 30px;gap:8px;align-items:center;margin-bottom:0;padding:12px;border-radius:12px}.task-main{display:flex;flex-direction:column;gap:2px;min-width:0;cursor:pointer}.task-main strong{display:flex;gap:6px;align-items:center;font-size:13px;font-weight:600}.task-main span{color:${C.muted};font-size:11px}.task-detail{grid-column:1 / -1;display:grid;gap:10px;padding:12px;background:${C.surface};border-radius:10px;border:1px solid ${C.border}}.drag{cursor:grab;color:${C.muted}}.drag:hover{color:${C.textDim}}.subtask-add{display:grid;grid-template-columns:1fr auto;gap:8px}.subtask-row{display:grid;grid-template-columns:24px 1fr auto;gap:8px;align-items:center}
      .complete{text-decoration:line-through;opacity:.45}.check{width:20px;height:20px;border-radius:6px;border:1.5px solid ${C.border};background:transparent;color:#08130f;display:grid;place-items:center;cursor:pointer;transition:background .12s,border-color .12s}.check:hover{border-color:${C.green}}.check.done{background:${C.green};border-color:${C.green}}
      .pill{display:inline-flex;justify-content:center;align-items:center;padding:3px 8px;border-radius:9999px;font-size:11px;font-weight:700;white-space:nowrap;letter-spacing:.01em}.icon-btn{width:28px;height:28px;border:0;border-radius:8px;background:transparent;color:${C.muted};display:grid;place-items:center;cursor:pointer;transition:background .12s,color .12s}.icon-btn:hover{background:${C.raised};color:${C.textDim}}.icon-btn.danger:hover{background:rgba(240,113,120,.14);color:${C.red}}
      .day-row{display:flex;flex-wrap:wrap;gap:6px;margin:12px 0}.day{border:1px solid ${C.border};background:transparent;color:${C.muted};border-radius:9999px;padding:5px 10px;font-size:11px;font-weight:700;cursor:pointer;transition:border-color .15s,color .15s,background .15s}.day:hover{border-color:${C.borderHi};color:${C.textDim}}.day.active{border-color:${C.purple};background:rgba(167,139,250,.12);color:${C.purple}}
      .recurring-row,.simple-row{display:grid;grid-template-columns:auto minmax(120px,1fr) auto auto minmax(120px,.5fr) auto;gap:10px;align-items:center;padding:10px 12px;background:${C.surface};border-radius:10px;border:1px solid transparent;transition:border-color .15s}.recurring-row:hover,.simple-row:hover{border-color:${C.border}}.recurring-row svg{color:${C.purple}}.simple-row{grid-template-columns:auto 52px 1fr auto}
      .currency-toolbar{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.segmented{display:flex;gap:2px;padding:3px;border:1px solid ${C.border};border-radius:10px;background:${C.surface}}.segmented button{border:0;border-radius:8px;background:transparent;color:${C.muted};font-size:11px;font-weight:700;padding:6px 10px;cursor:pointer;transition:background .12s,color .12s}.segmented button.active{background:${C.green};color:#071a12}
      .money-brief{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(240px,.65fr);gap:24px;align-items:center;border-color:rgba(52,212,164,.25);background:linear-gradient(135deg,rgba(52,212,164,.09),rgba(233,196,106,.05)),${C.glass}}.money-brief h3{font-size:clamp(18px,2.2vw,28px);font-weight:700;letter-spacing:-.015em;line-height:1.1;margin:4px 0 8px}.money-brief p{color:${C.muted};font-size:13px;max-width:680px}.cap-meter{padding:16px;border:1px solid ${C.border};border-radius:12px;background:rgba(0,0,0,.2)}.cap-meter strong{display:block;font-size:22px;color:${C.green};font-variant-numeric:tabular-nums;font-weight:700}.cap-meter span{display:block;color:${C.muted};font-size:11px;font-weight:600;margin-top:2px}.rate-line{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-top:10px;padding-top:10px;border-top:1px solid ${C.border}}.rate-line b{font-size:11px;color:${C.textDim}}.rate-error{margin-top:8px;color:${C.red};font-size:12px;font-weight:700}.progress-track{height:8px;margin-top:10px;border-radius:9999px;background:${C.surface};overflow:hidden;border:1px solid ${C.border}}.progress-track span{display:block;height:100%;border-radius:inherit;transition:width .5s ease}
      .money-layout{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(300px,.6fr);gap:16px}.expense-capture .card-head h3,.allocation-card .card-head h3,.money-section .card-head h3{display:flex;gap:7px;align-items:center}.expense-form{display:grid;grid-template-columns:140px minmax(200px,1fr) 100px 86px 150px auto;gap:8px;align-items:center}.draft-conversion{margin-top:8px;color:${C.muted};font-size:12px;font-weight:600}.category-builder{display:grid;grid-template-columns:minmax(160px,1fr) auto;gap:8px;margin-top:8px;max-width:420px}.expense-list{margin-top:16px}.expense-header{grid-template-columns:100px minmax(160px,1fr) 120px 140px 32px}.expense-row{display:grid;grid-template-columns:100px minmax(160px,1fr) 120px 140px 32px;gap:8px;align-items:center;padding:9px 10px;border-radius:10px;background:${C.surface};margin-top:6px;border:1px solid transparent;transition:border-color .15s}.expense-row:hover{border-color:${C.border}}.expense-row>span:first-child{color:${C.muted};font-size:11px;font-weight:600}.expense-row strong{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:500}.expense-row b{text-align:right;font-variant-numeric:tabular-nums;font-weight:700}.expense-row b small{display:block;color:${C.muted};font-size:10px;font-weight:600;margin-top:2px}.empty-inline{padding:12px 4px;color:${C.muted};font-size:12px;font-style:italic}.show-more{width:100%;margin-top:8px;background:transparent;border:1px dashed ${C.border};color:${C.muted};border-radius:8px;padding:8px;cursor:pointer;font-size:11px;font-weight:700;transition:border-color .15s,color .15s}.show-more:hover{border-color:${C.green};color:${C.green}}
      .allocation-list{display:grid;gap:8px}.allocation-row{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:10px 12px;border-radius:10px;background:${C.surface};border:1px solid transparent;transition:border-color .15s}.allocation-row:hover{border-color:${C.border}}.allocation-row span{display:block;color:${C.muted};font-size:11px;margin-top:2px}.allocation-row b{color:${C.green};white-space:nowrap;font-variant-numeric:tabular-nums;font-weight:700}
      .ai-advice{display:grid;gap:8px;margin-top:8px}.ai-advice p{color:${C.textDim};font-size:13px;line-height:1.65;margin:0;padding:10px 12px;border-radius:8px;background:${C.surface};border-left:2px solid ${C.green}}.groq-key-form{display:flex;gap:8px;align-items:center}
      .windfall-form{display:grid;grid-template-columns:160px 90px 1fr;gap:8px;align-items:center;margin-bottom:14px}.windfall-amd{color:${C.green};font-size:12px;font-weight:700;font-variant-numeric:tabular-nums}.windfall-splits{display:grid;gap:8px}.windfall-row{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:10px 12px;border-radius:10px;background:${C.surface}}.windfall-row span{display:block;color:${C.muted};font-size:11px;margin-top:2px}.windfall-row b{color:${C.green};white-space:nowrap;font-variant-numeric:tabular-nums;font-size:14px;font-weight:700}
      .finance-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:16px}.money-section{border-top-width:2px;overflow:hidden}.fin-header{display:grid;gap:8px;padding:0 4px;color:${C.muted};font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.08em;margin-bottom:8px}.fin-row{display:grid;gap:8px;align-items:center;padding:8px 10px;background:${C.surface};border-radius:8px;border:1px solid transparent;transition:border-color .15s}.fin-row:hover{border-color:${C.border}}.fin-totals{display:grid;gap:8px;padding:8px 10px 0;border-top:1px solid ${C.border};margin-top:8px;font-size:12px;font-weight:700;color:${C.text}}.fin-totals span:first-child{color:${C.muted}}
      .goal-fund-item{display:flex;flex-direction:column;gap:10px;padding:14px;background:${C.surface};border-radius:12px;border:1px solid ${C.border};transition:border-color .15s}.goal-fund-item:hover{border-color:${C.borderHi}}.goal-fund-head{display:flex;align-items:flex-start;gap:10px}.goal-fund-title{flex:1;min-width:0;display:flex;flex-direction:column;gap:4px}.goal-fund-meta{color:${C.muted};font-size:11px;font-weight:600;padding:0 2px}.goal-fund-bar{height:5px;background:rgba(255,255,255,.06);border-radius:9999px;overflow:hidden}.goal-fund-fill{height:100%;background:${C.blue};border-radius:inherit;transition:width .6s ease}.goal-fund-fields{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;align-items:end}.goal-fund-field{display:flex;flex-direction:column;gap:4px}.goal-fund-field label{color:${C.muted};font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.06em}
      .today-shell{display:grid;gap:20px}.hero-panel{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:32px;border:1px solid ${C.border};border-radius:24px;background:linear-gradient(135deg,rgba(52,212,164,.12),rgba(167,139,250,.06) 50%,rgba(233,196,106,.07));box-shadow:0 1px 0 rgba(255,255,255,.05) inset,0 8px 40px rgba(0,0,0,.32)}.hero-panel h2{font-size:clamp(26px,3.5vw,48px);font-weight:700;letter-spacing:-.02em;max-width:780px;line-height:1.05;margin:8px 0}.hero-panel p{color:${C.muted};font-weight:500;font-size:13px}.hero-meter{min-width:160px;border:1px solid ${C.border};border-radius:16px;padding:20px;background:rgba(8,8,18,.5);text-align:center}.hero-meter strong{display:block;color:${C.green};font-size:40px;font-weight:700;line-height:1;font-variant-numeric:tabular-nums}.hero-meter span{display:block;color:${C.muted};font-size:11px;font-weight:600;margin-top:6px}
      .verse-card{position:relative;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;overflow:hidden;border:1.5px solid #c9a24a;border-radius:20px;background:linear-gradient(145deg,#f5ebd4 0%,#ecdbb6 60%,#e4ceaa 100%);color:#111;box-shadow:0 2px 0 rgba(255,255,255,.6) inset,0 6px 28px rgba(160,120,30,.2);padding:32px 48px;gap:6px}.verse-card::after{content:"✝";position:absolute;right:20px;top:50%;transform:translateY(-50%);font-size:110px;line-height:1;color:rgba(100,65,10,.05);font-family:Georgia,serif;pointer-events:none}.verse-card>svg{color:#7a5010;flex-shrink:0;margin-bottom:4px}.verse-card span{display:block;text-transform:uppercase;letter-spacing:.16em;font-size:10px;font-weight:800;color:#7a5418 !important}.verse-card p{position:relative;font-family:Georgia,serif;font-size:clamp(15px,1.6vw,21px);line-height:1.7;margin:6px 0 10px;color:#111 !important;font-style:italic;font-weight:400;max-width:800px}.verse-card strong{display:block;text-align:center;color:#5a3c0e !important;font-size:12px;font-weight:700;letter-spacing:.05em}
      .today-grid{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(320px,.95fr);gap:16px}.today-task{display:grid;grid-template-columns:24px 1fr auto;gap:10px;align-items:center;padding:10px 12px;border-radius:10px;background:${C.surface};border:1px solid transparent;transition:border-color .15s}.today-task:hover{border-color:${C.border}}.today-task div{min-width:0}.today-task strong{display:block;font-size:13px;font-weight:600}.today-task span{display:block;color:${C.muted};font-size:11px;margin-top:1px}.quick-add{display:grid;grid-template-columns:1fr 140px auto auto;gap:8px;margin-top:16px}
      .week-strip{display:grid;grid-template-columns:repeat(7,1fr);gap:6px}.week-day{border:1px solid ${C.border};border-radius:12px;background:${C.surface};color:${C.text};padding:10px 6px;cursor:pointer;text-align:left;min-height:90px;transition:border-color .15s,background .15s}.week-day:hover{border-color:${C.borderHi};background:${C.raised}}.week-day.today{border-color:${C.green};box-shadow:0 0 0 2px rgba(52,212,164,.2)}.week-day.selected{border-color:${C.blue}}.week-day span,.week-day small{display:block;color:${C.muted};font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.05em}.week-day strong{display:block;font-size:20px;font-weight:700;margin:3px 0 8px}.dots{display:flex;gap:3px;min-height:7px}.dots i{width:6px;height:6px;border-radius:9999px}.selected-day-panel{margin-top:12px;padding:12px;border-radius:10px;background:${C.surface};border:1px solid ${C.border}}.selected-day-panel span{display:block;color:${C.blue};font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.08em;margin-bottom:8px}.selected-day-panel p{display:flex;justify-content:space-between;gap:10px;color:${C.text};font-size:12px;margin-top:6px}.selected-day-panel b{color:${C.muted};font-weight:500}
      .habit-pills{display:flex;flex-wrap:wrap;gap:8px}.habit-pill{border:1px solid ${C.border};border-radius:9999px;background:${C.surface};color:${C.text};padding:8px 14px;display:flex;gap:7px;align-items:center;cursor:pointer;font-weight:600;font-size:12px;transition:border-color .15s,background .15s}.habit-pill:hover{border-color:${C.borderHi};background:${C.raised}}.habit-pill svg{color:${C.muted}}.habit-pill.on{border-color:${C.green};background:rgba(52,212,164,.1)}.habit-pill.on svg{color:${C.green}}.habit-pill b{min-width:20px;height:20px;border-radius:9999px;background:rgba(233,196,106,.15);color:${C.amber};display:grid;place-items:center;font-size:10px;font-weight:700}
      .habit-table{display:grid;grid-template-columns:minmax(210px,1fr) repeat(7,minmax(40px,68px));gap:6px;align-items:center;overflow-x:auto}.habit-date{text-align:center;color:${C.muted};font-weight:700;font-size:11px}.habit-date span{display:block;font-weight:500;font-size:10px;color:${C.muted};margin-top:1px}.habit-name{display:grid;grid-template-columns:1fr 56px auto;align-items:center;gap:8px;padding:4px 0}.habit-name span{display:block;color:${C.muted};font-size:11px}.habit-cell{height:36px;border:1px solid ${C.border};background:${C.surface};color:#08130f;border-radius:8px;display:grid;place-items:center;cursor:pointer;transition:background .12s,border-color .12s}.habit-cell:hover{border-color:${C.green};background:rgba(52,212,164,.08)}.habit-cell.on{background:${C.green};border-color:${C.green}}
      .review-editor label{display:block;color:${C.muted};font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.07em;margin-bottom:8px}.review-top{display:grid;grid-template-columns:160px 1fr 1fr;gap:16px;margin-bottom:16px}.rating{display:flex;gap:4px}.rating button{width:32px;height:32px;border:1px solid ${C.border};border-radius:8px;background:${C.surface};color:${C.muted};display:grid;place-items:center;cursor:pointer;transition:border-color .12s,color .12s,background .12s}.rating button.on{color:${C.amber};border-color:${C.amber};background:rgba(233,196,106,.12)}.review-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.review-summary{display:flex;gap:10px;flex-wrap:wrap;color:${C.muted};font-size:12px;margin-bottom:12px}.stars{color:${C.amber};letter-spacing:1px}
      .cards-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px}.charts-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(400px,1fr));gap:16px}.stats-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:12px;margin-bottom:20px}.stat{margin:0}.stat span{display:block;color:${C.muted};font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.06em;margin-bottom:6px}.stat strong{font-size:22px;font-weight:700;font-variant-numeric:tabular-nums;letter-spacing:-.01em}
      .progress{height:6px;background:${C.surface};border-radius:9999px;overflow:hidden;margin:12px 0;border:1px solid ${C.border}}.progress span{display:block;height:100%;background:${C.green};border-radius:inherit}.split{display:grid;grid-template-columns:1fr 80px auto;gap:8px}
      .chart-box{height:280px;min-width:0}.chart-tip{background:${C.card};border:1px solid ${C.border};border-radius:8px;padding:8px 10px;font-size:12px;box-shadow:0 4px 16px rgba(0,0,0,.3)}.chart-tip b{display:block;color:${C.text};font-weight:700;margin-bottom:4px}
      .analytics-shell{display:flex;flex-direction:column;gap:0}.analytics-section{margin-top:32px;padding-top:32px;border-top:1px solid ${C.border}}.chart-full{grid-column:1 / -1}
      .ai-chat-input{display:flex;gap:8px;align-items:center;margin-bottom:12px}.ai-history{display:flex;flex-direction:column;gap:12px;margin-top:4px;max-height:480px;overflow-y:auto}.ai-exchange{display:flex;flex-direction:column;gap:6px;padding:12px;border-radius:10px;background:${C.surface};border:1px solid ${C.border}}.ai-q{font-size:12px;font-weight:700;color:${C.textDim};display:flex;flex-direction:column;gap:2px}.ai-q span{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:${C.muted}}.ai-a p{color:${C.text};font-size:13px;line-height:1.65;margin:0 0 4px;padding:8px 10px;border-radius:8px;background:${C.card};border-left:2px solid ${C.green}}.ai-suggestions{display:flex;flex-wrap:wrap;gap:8px;margin-top:8px}.ai-suggestion-chip{border:1px solid ${C.border};border-radius:9999px;background:transparent;color:${C.muted};padding:6px 12px;font-size:12px;font-weight:600;cursor:pointer;transition:border-color .15s,color .15s}.ai-suggestion-chip:hover{border-color:${C.green};color:${C.green}}
      .notice{border:1px solid rgba(52,212,164,.3);background:rgba(52,212,164,.08);color:${C.green};border-radius:10px;padding:10px 14px;font-weight:700;font-size:12px;margin-bottom:14px}.empty{padding:32px;text-align:center;color:${C.muted};font-style:italic;font-size:13px}
      .modal-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.72);display:grid;place-items:center;z-index:50;padding:20px;backdrop-filter:blur(4px)}.modal{width:min(460px,100%);margin:0}.modal h2{font-size:18px;font-weight:700;letter-spacing:-.01em;margin-bottom:8px}.modal p{color:${C.muted};font-size:13px;margin-bottom:16px}.upload-btn{display:flex;align-items:center;justify-content:center;gap:8px;background:${C.raised};border-radius:10px;padding:10px 14px;font-weight:700;cursor:pointer;margin:10px 0;border:1px solid ${C.border};transition:border-color .15s}.upload-btn:hover{border-color:${C.green}}.upload-btn input{display:none}
      .focus-bar{position:fixed;left:50%;bottom:20px;transform:translateX(-50%);z-index:40;width:min(880px,calc(100% - 32px));display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:14px;align-items:center;padding:12px 16px;border:1px solid ${C.border};border-radius:16px;background:rgba(12,12,26,.95);backdrop-filter:blur(20px) saturate(1.5);box-shadow:0 8px 40px rgba(0,0,0,.5),0 1px 0 rgba(255,255,255,.05) inset}.focus-bar.running{border-color:${C.green};animation:pulse 2.8s ease-in-out infinite}.focus-bar span{display:block;color:${C.muted};font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.12em}.focus-bar strong{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-weight:600}.focus-bar time{font-size:26px;font-weight:700;color:${C.green};font-variant-numeric:tabular-nums}
      @media (max-width:900px){.section-title,.topbar,.hero-panel{align-items:flex-start;flex-direction:column}.tabs{top:120px}.today-grid,.money-brief,.money-layout{grid-template-columns:1fr}.quick-add,.task-grid,.template-grid,.routine-grid,.goal-grid,.review-top,.review-grid,.expense-form{grid-template-columns:1fr}.task-row{grid-template-columns:28px 24px minmax(0,1fr) auto}.task-row>.pill,.task-row>.field,.task-row>.btn{grid-column:3 / -1}.recurring-row{grid-template-columns:1fr 1fr}.recurring-row svg{display:none}.habit-table{grid-template-columns:minmax(180px,1fr) repeat(7,40px)}.focus-bar{grid-template-columns:1fr}.week-strip{grid-template-columns:repeat(7,minmax(72px,1fr));overflow-x:auto}.week-day{min-width:72px}.finance-grid{grid-template-columns:1fr}.expense-row,.expense-header{grid-template-columns:80px minmax(130px,1fr) 100px 90px 30px}}
      @media (max-width:560px){main{padding-top:20px}.brand h1{font-size:16px}.tabs{top:114px}.stats-grid,.cards-grid,.charts-grid{grid-template-columns:1fr}.section-heading h2{font-size:18px}.task-row{padding:10px}.fin-row,.fin-header,.fin-row-wide,.fin-header-wide,.expense-row,.expense-header,.category-builder{grid-template-columns:1fr !important}.chart-box{height:220px}.hero-panel{padding:20px}.hero-meter{width:100%}.verse-card{grid-template-columns:1fr}.planning-badge span{white-space:normal}.expense-row b{text-align:left}.fund-progress{position:static;grid-column:1 / -1}.windfall-form{grid-template-columns:1fr}}
    `}</style>
  );
}
